thermos/models.py
from datetime import datetime
from flask_login import UserMixin
from sqlalchemy import desc
from werkzeug.security import check_password_hash, generate_password_hash

from thermos import db


tags = db.Table('bookmark_tag',
               db.Column('tag_id', db.Integer, db.ForeignKey('tag.id')),
               db.Column('bookmark_id', db.Integer, db.ForeignKey('bookmark.id'))
               )


class Bookmark(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.Text, nullable=False)
    date = db.Column(db.DateTime, default=datetime.utcnow)
    description = db.Column(db.String(300))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    _tags = db.relationship('Tag', secondary=tags, lazy='joined', backref=db.backref('bookmarks', lazy='dynamic'))
    
    @staticmethod
    def newest(num):
        return Bookmark.query.order_by(desc(Bookmark.date)).limit(num)

    @property
    def tags(self):
        return ",".join([t.name for t in self._tags])
    
    #inserts new tag into the db if the tag does not already exist in the db
    @tags.setter
    def tags(self, string):
        if string:
            self._tags = [Tag.get_or_create(name) for name in string.split(',')]
        else:
            self._tags = []
        
    def __repr__(self):
        return "<Bookmark '{}' : '{}'>".format(self.description, self.url)
    
class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)
    email = db.Column(db.String(120), unique=True)
    bookmarks = db.relationship('Bookmark', backref='user', lazy='dynamic')
    password_hash = db.Column(db.String)
    
    @property
    def password(self):
        raise AttributeError('password: write-only field')
        
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)
        
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)
    
    @staticmethod
    def get_by_username(username):
        return User.query.filter_by(username=username).first()
    
    def __repr__(self):
        return '<User %r>' % self.username
    
    
class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(25), nullable=False, unique=True, index=True)
    
    @staticmethod
    def get_or_create(name):
        try:
            return Tag.query.filter_by(name=name).one()
        except:
            return Tag(name=name)
    
    @staticmethod
    def all():
        return Tag.query.all()
    
    def __repr__(self):
        return self.name

thermos/bookmarks/forms.py
from flask_wtf import Form
from wtforms.fields import StringField
from flask.ext.wtf.html5 import URLField
from wtforms.validators import DataRequired, url, Regexp


class BookmarkForm(Form):
    url = URLField('The URL for your bookmark', validators=[DataRequired(),url()])
    description = StringField('Add a description', validators=[DataRequired()])
    tags = StringField('Tags', validators=[Regexp(r'^[a-zA-Z0-9, ]*$',
                                                 message="Tags can only contain letters and numbers")])
    
    def validate(self):
        if not self.url.data.startswith("http://") or self.url.data.startswith("https://"):
                self.url.data = "http://" + self.url.data
                
        if not Form.validate(self):
            return False
        
        if not self.description.data:
            self.description.data = self.url.data
            
        #Filter out any duplicated tags
        stripped = [t.strip() for t in self.tags.data.split(',')]
        not_empty = [tag for tag in stripped if tag]
        tagset = set(not_empty)
        self.tags.data = ",".join(tagset)

        return True
    

thermos/forms.py
from flask_wtf import Form
from wtforms.fields import StringField, PasswordField, BooleanField, SubmitField
from flask.ext.wtf.html5 import URLField
from wtforms.validators import DataRequired, url, Regexp, Length, EqualTo, Email, ValidationError
from models import User

class BookmarkForm(Form):
    url = URLField('The URL for your bookmark', validators=[DataRequired(),url()])
    description = StringField('Add a description', validators=[DataRequired()])
    tags = StringField('Tags', validators=[Regexp(r'^[a-zA-Z0-9, ]*$',
                                                 message="Tags can only contain letters and numbers")])
    
    def validate(self):
        if not self.url.data.startswith("http://") or self.url.data.startswith("https://"):
                self.url.data = "http://" + self.url.data
                
        if not Form.validate(self):
            return False
        
        if not self.description.data:
            self.description.data = self.url.data
            
        #Filter out any duplicated tags
        stripped = [t.strip() for t in self.tags.data.split(',')]
        not_empty = [tag for tag in stripped if tag]
        tagset = set(not_empty)
        self.tags.data = ",".join(tagset)

        return True
    
class LoginForm(Form):
    username = StringField('Your Username: ', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Keep me logged in')
    submit = SubmitField('Log In')
    
class SignupForm(Form):
    username = StringField('Username', 
                          validators=[ DataRequired(), Length(5, 45),
                                     Regexp('^[A-Za-z0-9_]{3,}$',
                                           message='Username consists of numbers, letters, and underscores')])
    password = PasswordField('Password', validators=[DataRequired(),
                                                    EqualTo('password2', message='Passwords must match.')])
    password2 = PasswordField('Confirm Password', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Length(1,65), Email()])
    submit = SubmitField('Sign Up')
    
    def validate_email(self, email_field):
        if User.query.filter_by(email=email_field.data).first():
            raise ValidationError('An account with this email has already been created.')
        
    def validate_username(self, username_field):
        if User.query.filter_by(username=username_field.data).first():
            raise ValidationError('This username is taken.')
            

thermos/__init__.py
import os

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask.ext.moment import Moment
from flask_debugtoolbar import DebugToolbarExtension

from .config import config_by_name

db = SQLAlchemy()

#configure authentication
login_manager = LoginManager()
login_manager.session_protection = "strong"
login_manager.login_view = "auth.login"

#enable debugtoolbar - 'DEBUG' config must be set to True
toolbar = DebugToolbarExtension()

# for displaying timestamps
moment = Moment()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_by_name[config_name])
    db.init_app(app)
    login_manager.init_app(app)
    moment.init_app(app)
    toolbar.init_app(app)
    
    #Register the main package
    from .main import app as main_blueprint
    app.register_blueprint(main_blueprint, url_prefix='')
    
    #Register the auth package
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    #Register the bookmarks package
    from .bookmarks import bookmarks as bookmarks_blueprint
    app.register_blueprint(bookmarks_blueprint, url_prefix='/bookmark')

    return app

thermos/bookmarks/__init__.py
from flask import Blueprint

bookmarks = Blueprint('bookmarks', __name__)

from . import views

thermos/bookmarks/views.py
from flask import Flask, render_template, request, redirect, url_for, flash, abort
from flask_login import login_required, current_user

from . import bookmarks
from .. import db
from ..models import User, Bookmark, Tag
from .forms import BookmarkForm


    
@bookmarks.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('user.html', user=user)


@bookmarks.route('/add', methods=['GET', 'POST'])
@login_required
def add(): 
    form = BookmarkForm()
    if form.validate_on_submit():
        url = form.url.data.lower()
        description = form.description.data
        tags = form.tags.data
        bm = Bookmark(user=current_user, url=url, description=description, tags=tags)
        db.session.add(bm)
        db.session.commit()
        flash("Stored '{}'".format(url))
        return redirect(url_for('app.index'))
    return render_template('bookmark_form.html', form=form, title="Add a Bookmark")


@bookmarks.route('/edit/<int:bookmark_id>', methods=['GET', 'POST'])
@login_required
def edit(bookmark_id):
    bookmark = Bookmark.query.get_or_404(bookmark_id)
    if current_user != bookmark.user:
        abort(403)
    form = BookmarkForm(obj=bookmark)
    if form.validate_on_submit():
        form.populate_obj(bookmark)
        db.session.commit()
        flash("Stored '{}'".format(bookmark.description))
        return redirect(url_for('.user', username=current_user.username))
    return render_template('bookmark_form.html', form=form, title="Edit Bookmark")


@bookmarks.route('/delete/<int:bookmark_id>', methods=['GET', 'POST'])
@login_required
def delete_bookmark(bookmark_id):
    bookmark = Bookmark.query.get_or_404(bookmark_id)
    if current_user != bookmark.user:
        abort(403)
    if request.method == 'POST':
        db.session.delete(bookmark)
        db.session.commit()
        flash("Deleted '{}'".format(bookmark.description))
        return redirect(url_for('.user', username=current_user.username))
    else:
        flash("Please confirm deleting the bookmark")
    return render_template('confirm_delete.html', bookmark=bookmark, nolinks=True)


@bookmarks.route('/tag/<name>')
def tag(name):
    tag = Tag.query.filter_by(name=name).first_or_404()
    return render_template('tag.html', tag=tag)

thermos/main/__init__.py
from flask import Blueprint

app = Blueprint('app', __name__)

from . import views

thermos/main/views.py
from flask import render_template

from . import app
from .. import login_manager
from ..models import User, Bookmark, Tag

@login_manager.user_loader
def load_user(userid):
    return User.query.get(int(userid))

@app.route('/')
@app.route('/index')
def index():
     return render_template('index.html', new_bookmarks=Bookmark.newest(5))


#Error handling
@app.app_errorhandler(403)
def unauthorized(e):
    return render_template('403.html'), 403


@app.app_errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


@app.app_errorhandler(500)
def server_error(e):
    return render_template('500.html', error=e), 500

#Global additions
@app.app_context_processor
def inject_tags():
    return dict(all_tags=Tag.all)

thermos/templates/base.html
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Stylesheets -->
        {% block styles %}
            <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-theme.min.css')}}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css')}}">
        {% endblock %}
        
    </head>
    <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('app.index')}}">Thermos</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse pull-right">
          <ul class="nav navbar-nav">
              {% if current_user.is_authenticated %}
                  <li><a href="{{ url_for('bookmarks.add')}}">Add URL</a></li>
                  <li><a href="{{ url_for('auth.logout')}}">Logout</a></li>
              {% else %}
                  <li><a href="{{ url_for('auth.login')}}">Login</a></li>
                  <li><a href="{{ url_for('auth.signup')}}">Sign Up</a></li>
              {% endif %}        
          </ul>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul class="add flash">
        {% for message in messages %}
          <li><b>{{ message }}</b></b></li>
        {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
    <div class="jumbotron">
      <div class="container">
        {% block jumbo %}
        {% endblock %}
      </div>
    </div>

    {% block content %}
    {% endblock %}

      <hr>

      <footer>
        <p>&copy; Company 2015</p>
      </footer>
        <!-- scripts -->    
        {{ moment.include_jquery() }}
        {{ moment.include_moment() }}

        {% block scripts %}
            <script src="../static/scripts/vendor/bootstrap.min.js"></script>
            <script src="../static/scripts/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>
            <script src="../static/scripts/main.js"></script>
        {% endblock %}
    </body>
</html>

thermos/templates/bookmark.html
<a href="{{ bookmark.url }}" class="header">
    <h3 class="description">
        {% if bookmark.description %}
            {{ bookmark.description|truncate(50,True)}}
        {% else %}
            No Description
        {% endif %}
    </h3>
    <span class="url">
        {{ bookmark.url|truncate(50,True) }}
    </span>
</a>
<div class="info">
       <div class="tags">
        {% if bookmark.tags %}
            {% for t in bookmark._tags %}
                <a href="{{ url_for('bookmarks.tag', name=t)}}">{{ t }}</a>
            {% endfor %}
        {% else %}
            <p>No Tags</p>
        {% endif %}
        </div>

    Added by
    <a href="{{ url_for('bookmarks.user', username=bookmark.user.username )}}">
        {{ bookmark.user.username }}
    </a>
    {{ moment(bookmark.date).fromNow() }}    
</div>

thermos/templates/bookmark_form.html
{% extends 'base.html' %}
{% from "form_macros.html" import render_field %}

{% block title %}
    {{ title }}
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static', filename='css/select2.css')}}">
{% endblock %}

{% block jumbo %}
    <h1>{{ title }}</h1>
    <form id="add_bookmark" action="" method="post">
        {{form.hidden_tag()}}        
        {{render_field(form.url,size=50, class="form-group col-md-6 col-sm-10")}}
        {{render_field(form.description, size=50, class="form-group col-md-6 col-sm-10")}}
        {{render_field(form.tags, size=50, class="form-group col-md-6 col-sm-10", id="tags")}}
        <div class="form-group row">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
{% endblock %}
    
{% block content %}
    <h6>ROOOAAAR!!!</h6>
{% endblock %}


{% block scripts %}
    <script src="{{url_for('static', filename='scripts/vendor/select2.min.js')}}"></script>
    <script>
        $(document).ready(function(){
            var _tags = {{ all_tags()|map(attribute='name')|list|tojson|safe }};
            $('#tags').select2({tags: _tags, tokenSeparators: [",", " "]});
        });
    </script>
{% endblock %}

thermos/templates/bookmark_list.html
<ul class="bookmarks">
    {% for bookmark in bookmarks %}
        <li>
            {% include "bookmark.html" %}
            {% if current_user == bookmark.user %}
                <span class="editlinks pull-right col-md-4">
                    <a href="{{url_for('bookmarks.delete_bookmark', bookmark_id=bookmark.id )}}">delete</a>
                </span>
                <span class="editlinks pull-right">
                    <a href="{{url_for('bookmarks.edit', bookmark_id=bookmark.id )}}">edit</a>
                </span>
            {% endif %}
            <hr>
        </li>
    {% endfor %}
</ul>

thermos/templates/confirm_delete.html
{% extends "base.html" %}


{% block title %}
Delete Bookmark
{% endblock %}



{% block content %}
    <h1>Confirm delete</h1>
    {% include "bookmark.html" %}
    
    <form action="" method="post">
        <span style="color:red">Are you sure you want to delete this post?</span>
        <br>
        <a href="{{url_for('bookmarks.user',username=current_user.username)}}">
            <button type="button" class="btn btn-warning">
                No, Take me out of here!
            </button>
        </a>
        <button type="submit" class="btn btn-danger">Yes, delete it</button>
    </form>
{% endblock%}

thermos/templates/form_macros.html
{% macro render_field(field) %}
    <div class="form-group row">
         <label class="col-sm-3 add_label {% if field.errors %}error{% endif %}">
            {{field.label}}
        </label>
        <div class="col-sm-9">
            {{ field(**kwargs)|safe }}
        </div>
        <ul>
            {% for error in field.errors %}
                <li class="flash-error">{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
 {% endmacro %}
 

thermos/templates/index.html
{% extends "base.html" %}

      
 {% block title%}
     Thermos -- Welcome
 {% endblock %}


         <!-- Main jumbotron for a primary marketing message or call to action -->
{% block jumbo %}
    <h1>Welcome to Thermos!</h1>
    <h4>Thermos is a simple social bookmarking site.</h4>
    <p><a class="btn btn-success" href="{{ url_for('bookmarks.add')}}" role="button">Add a bookmark</a></p>
{% endblock %}
 
 
 
 {% block content %}
    <div class="row" id="main-content">
        <div class="col-md-6">
            <h2>Current Bookmarks</h2>
            {% if new_bookmarks.count() > 0 %}
                {% with bookmarks=new_bookmarks %}
                    {% include "bookmark_list.html" %}
                {% endwith %}
            {% else %}
                <h2>No bookmarks currently saved</h2>
                <p>Be the first to <a href="{{ url_for('bookmarks.add')}}"><b>add!</b></a></p>
            {% endif %}
        </div>
        <div class="col-md-6">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
          <hr>
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

 {% endblock %}

thermos/templates/login.html
{% extends 'base.html' %}
{% from "form_macros.html" import render_field %}

{% block title %}
Login
{% endblock %}


{% block jumbo %}
    <h1>Login</h1>
    <form id="Login" action="" method="post">
        {{form.hidden_tag()}}        
        {{render_field(form.username, size=50, class="form-group")}}
        {{render_field(form.password, size=50, class="form-group")}}
        {{render_field(form.remember_me, class="form-group")}}
        {{render_field(form.submit, class="btn btn-primary")}}
    </form>
{% endblock %}

thermos/templates/navbar.html
{% extends "base.html" %}


{% block navbar %}
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('index')}}">Thermos</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" role="form">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>
{% endblock %}

thermos/templates/signup.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block title %}
    SignUp/Register
{% endblock %}

{% block jumbo %}
    <h1>Signup/Register</h1>
    <form action="" method="post" id="signup">
        {{form.hidden_tag()}}
        {{ render_field(form.username, size=50, class="form-group")}}
        {{ render_field(form.email, size=50, class="form-group")}}
        {{ render_field(form.password, size=50, class="form-group")}}
        {{ render_field(form.password2, size=50, class="form-group")}}
        {{ render_field(form.submit, class="btn btn-primary")}}
    </form>
{% endblock %}

thermos/templates/tag.html
{% extends "base.html" %}


{% block title %}
Bookmarks tagged {{ tag }}
{% endblock %}


{% block jumbo %}
<h2>Bookmarks tagged {{ tag }}</h2>
{% endblock %}


{% block content %}
{% if tag.bookmarks.count() > 0 %}
    {% with bookmarks=tag.bookmarks %}
        {% include "bookmark_list.html" %}
    {% endwith %}
{% else %}
    <h3>No bookmarks tagged with {{ tag }}</h3>
{% endif %}

{% endblock %}

thermos/templates/user.html
{% extends "base.html" %}


{% block title %}
    Thermos - {{user.username}}'s Bookmarks
{% endblock %}

{% block jumbo %}
    <h1>Bookmarks for {{ user.username}}</h1>
{% endblock %}

{% block content %}
    {% if user.bookmarks.count() > 0 %}
        {% with bookmarks = user.bookmarks %}
            {% include "bookmark_list.html" %}
        {% endwith %}
    {% else %}
        <h3>No Bookmarks Added</h3>
    {% endif %}
{% endblock %}